### ISSUE TITLE
need a sample for saga compensating in case failure

### ISSUE THREAD

**Issue by bvarg** [AMVSoftware/NSaga#39]
need a sample for saga compensating in case failure

**Comment by trailmax** [comment]
@bvarg Can you elaborate please? what is "compensating" and what is "failure" in your case?

**Comment by bvarg** [comment]
I am referring on how to implement a distributed business transaction using NSaga and ensuring the data consistency across calling different services using Sagas when one of the saga execution fails and I need to rollback(Compensating) the previous saga actions during this chain of execution. Like the state machine and routing slip in MassTransit 

https://dzone.com/articles/distributed-sagas-for-microservices

**Comment by trailmax** [comment]
@bvarg I think your scenario might not be suitable for this library. Not really aiming for this level of complexity.

**Comment by bvarg** [comment]
thank you
